src/Entity/Skills.php
<?php

namespace App\Entity;

use App\Repository\SkillsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SkillsRepository::class)]
class Skills
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $cursus_order = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $short_name = null;

    /**
     * @var Collection<int, LessonSessions>
     */
    #[ORM\ManyToMany(targetEntity: LessonSessions::class, inversedBy: 'skills')]
    private Collection $lesson_sessions;

    #[ORM\ManyToOne(inversedBy: 'skills')]
    #[ORM\JoinColumn(nullable: true)]
    private ?TopicsGroups $topics_group = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $inactive = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $professional = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $knowledge = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $performance = null;

    #[ORM\ManyToOne(inversedBy: 'skills')]
    private ?Users $teacher = null;

    #[ORM\Column(nullable: true)]
    private ?float $volume = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $period = null;

    public function __construct()
    {
        $this->lesson_sessions = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getShortName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCursusOrder(): ?int
    {
        return $this->cursus_order;
    }

    public function setCursusOrder(?int $cursus_order): static
    {
        $this->cursus_order = $cursus_order;

        return $this;
    }

    public function getShortName(): ?string
    {
        return $this->short_name;
    }

    public function setShortName(?string $short_name): static
    {
        $this->short_name = $short_name;

        return $this;
    }

    /**
     * @return Collection<int, LessonSessions>
     */
    public function getLessonSessions(): Collection
    {
        return $this->lesson_sessions;
    }

    public function addLessonSession(LessonSessions $lessonSession): static
    {
        if (!$this->lesson_sessions->contains($lessonSession)) {
            $this->lesson_sessions->add($lessonSession);
        }

        return $this;
    }

    public function removeLessonSession(LessonSessions $lessonSession): static
    {
        $this->lesson_sessions->removeElement($lessonSession);

        return $this;
    }

    public function getTopicsGroup(): ?TopicsGroups
    {
        return $this->topics_group;
    }

    public function setTopicsGroup(?TopicsGroups $topics_group): static
    {
        $this->topics_group = $topics_group;

        return $this;
    }

    public function getInactive(): ?\DateTimeInterface
    {
        return $this->inactive;
    }

    public function setInactive(?\DateTimeInterface $inactive): static
    {
        $this->inactive = $inactive;

        return $this;
    }

    public function getProfessional(): ?string
    {
        return $this->professional;
    }

    public function setProfessional(?string $professional): static
    {
        $this->professional = $professional;

        return $this;
    }

    public function getKnowledge(): ?string
    {
        return $this->knowledge;
    }

    public function setKnowledge(?string $knowledge): static
    {
        $this->knowledge = $knowledge;

        return $this;
    }

    public function getPerformance(): ?string
    {
        return $this->performance;
    }

    public function setPerformance(?string $performance): static
    {
        $this->performance = $performance;

        return $this;
    }

    public function getTeacher(): ?Users
    {
        return $this->teacher;
    }

    public function setTeacher(?Users $teacher): static
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getVolume(): ?float
    {
        return $this->volume;
    }

    public function setVolume(?float $volume): static
    {
        $this->volume = $volume;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(?string $period): static
    {
        $this->period = $period;

        return $this;
    }
}

src/Entity/Trainings.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Config\UsersRolesTrainingsEnum;
use App\Config\UsersStatusTrainingsEnum;
use App\Repository\TrainingsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrainingsRepository::class)]
#[ApiResource]
class Trainings
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $inactive = null;

    #[ORM\ManyToOne(inversedBy: 'trainings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Places $place = null;

    #[ORM\OneToMany(mappedBy: 'trainings', targetEntity: TopicsTrainings::class)]
    private Collection $trainings;

    #[ORM\OneToMany(mappedBy: 'training', targetEntity: TimeSlots::class)]
    private Collection $timeSlots;

    #[ORM\OneToMany(mappedBy: 'training', targetEntity: LessonSessions::class)]
    private Collection $lessonSessions;

    #[ORM\ManyToOne(inversedBy: 'trainings')]
    private ?Cursus $cursus = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shortTitle = null;

    #[ORM\ManyToOne(inversedBy: 'trainings')]
    private ?TrainingsModality $trainingsModality = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $startTrainingDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $endTrainingDate = null;

    #[ORM\ManyToOne(inversedBy: 'trainingsContentContact')]
    private ?Users $contentContact = null;

    #[ORM\ManyToOne(inversedBy: 'trainingsScholarshipContact')]
    private ?Users $scholarshipContact = null;

    #[ORM\ManyToOne(inversedBy: 'trainingsAdministrativeContact')]
    private ?Users $administrativeContact = null;

    #[ORM\Column(nullable: true)]
    private ?bool $activateFinancialManagement = null;

    #[ORM\ManyToOne(inversedBy: 'trainingsDefaultClassRoom')]
    private ?ClassRooms $defaultClassRoom = null;

    #[ORM\OneToMany(targetEntity: TrainingFinancialItems::class, mappedBy: 'training')]
    private Collection $trainingFinancialItems;

    /**
     * @var Collection<int, UsersTrainings>
     */
    #[ORM\OneToMany(targetEntity: UsersTrainings::class, mappedBy: 'training')]
    private Collection $usersTrainings;

    /**
     * @var Collection<int, TrainingsOptions>
     */
    #[ORM\OneToMany(targetEntity: TrainingsOptions::class, mappedBy: 'training')]
    private Collection $trainingsOptions;

    public function __construct()
    {
        $this->trainings = new ArrayCollection();
        $this->timeSlots = new ArrayCollection();
        $this->lessonSessions = new ArrayCollection();
        $this->trainingFinancialItems = new ArrayCollection();
        $this->usersTrainings = new ArrayCollection();
        $this->trainingsOptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getLevel(): string
    {
        if(!empty($this->getCursus())) {
            return $this->getCursus()->getType()->getLevel();
        }
        return '';
    }

    public function getInactive(): ?\DateTimeInterface
    {
        return $this->inactive;
    }

    public function setInactive(?\DateTimeInterface $inactive): static
    {
        $this->inactive = $inactive;

        return $this;
    }

    public function getPlace(): ?Places
    {
        return $this->place;
    }

    public function setPlace(?Places $place): static
    {
        $this->place = $place;

        return $this;
    }

    public function __toString() : string {
        return $this->getTitle();
    }

    /**
     * @return Collection<int, TopicsTrainings>
     */
    public function getTrainings(): Collection
    {
        return $this->trainings;
    }

    public function addTraining(TopicsTrainings $training): static
    {
        if (!$this->trainings->contains($training)) {
            $this->trainings->add($training);
            $training->setTrainings($this);
        }

        return $this;
    }

    public function removeTraining(TopicsTrainings $training): static
    {
        if ($this->trainings->removeElement($training)) {
            // set the owning side to null (unless already changed)
            if ($training->getTrainings() === $this) {
                $training->setTrainings(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, TopicsGroups>
     */
    public function getTopicsGroups(): Collection
    {
        return $this->getCursus()->getTopicsGroups();
    }

    /**
     * @return Collection<int, TimeSlots>
     */
    public function getTimeSlots(): Collection
    {
        return $this->timeSlots;
    }

    public function addTimeSlot(TimeSlots $timeSlot): static
    {
        if (!$this->timeSlots->contains($timeSlot)) {
            $this->timeSlots->add($timeSlot);
            $timeSlot->setTraining($this);
        }

        return $this;
    }

    public function removeTimeSlot(TimeSlots $timeSlot): static
    {
        if ($this->timeSlots->removeElement($timeSlot)) {
            // set the owning side to null (unless already changed)
            if ($timeSlot->getTraining() === $this) {
                $timeSlot->setTraining(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LessonSessions>
     */
    public function getLessonSessions(): Collection
    {
        return $this->lessonSessions;
    }

    public function addLessonSession(LessonSessions $lessonSession): static
    {
        if (!$this->lessonSessions->contains($lessonSession)) {
            $this->lessonSessions->add($lessonSession);
            $lessonSession->setTraining($this);
        }

        return $this;
    }

    public function removeLessonSession(LessonSessions $lessonSession): static
    {
        if ($this->lessonSessions->removeElement($lessonSession)) {
            // set the owning side to null (unless already changed)
            if ($lessonSession->getTraining() === $this) {
                $lessonSession->setTraining(null);
            }
        }

        return $this;
    }
    
    public function getCursus(): ?Cursus
    {
        return $this->cursus;
    }

    public function setCursus(?Cursus $cursus): static
    {
        $this->cursus = $cursus;

        return $this;
    }

    public function getShortTitle(): ?string
    {
        return $this->shortTitle;
    }

    public function setShortTitle(?string $shortTitle): static
    {
        $this->shortTitle = $shortTitle;

        return $this;
    }

    public function getShortDisplayName() : string {
        return empty($this->getShortTitle()) ? $this->getTitle() : $this->getShortTitle();
    }

    public function getTrainingsModality(): ?TrainingsModality
    {
        return $this->trainingsModality;
    }

    public function setTrainingsModality(?TrainingsModality $trainingsModality): static
    {
        $this->trainingsModality = $trainingsModality;

        return $this;
    }

    public function getStartTrainingDate(): ?\DateTimeInterface
    {
        return $this->startTrainingDate;
    }

    public function setStartTrainingDate(?\DateTimeInterface $startTrainingDate): static
    {
        $this->startTrainingDate = $startTrainingDate;

        return $this;
    }

    public function getEndTrainingDate(): ?\DateTimeInterface
    {
        return $this->endTrainingDate;
    }

    public function setEndTrainingDate(?\DateTimeInterface $endTrainingDate): static
    {
        $this->endTrainingDate = $endTrainingDate;

        return $this;
    }

    public function getContentContact(): ?Users
    {
        return $this->contentContact;
    }

    public function setContentContact(?Users $contentContact): static
    {
        $this->contentContact = $contentContact;

        return $this;
    }

    public function getScholarshipContact(): ?Users
    {
        return $this->scholarshipContact;
    }

    public function setScholarshipContact(?Users $scholarshipContact): static
    {
        $this->scholarshipContact = $scholarshipContact;

        return $this;
    }

    public function getAdministrativeContact(): ?Users
    {
        return $this->administrativeContact;
    }

    public function setAdministrativeContact(?Users $administrativeContact): static
    {
        $this->administrativeContact = $administrativeContact;

        return $this;
    }

    public function isActivateFinancialManagement(): ?bool
    {
        return $this->activateFinancialManagement;
    }

    public function setActivateFinancialManagement(?bool $activateFinancialManagement): static
    {
        $this->activateFinancialManagement = $activateFinancialManagement;

        return $this;
    }

    public function getDefaultClassRoom(): ?ClassRooms
    {
        return $this->defaultClassRoom;
    }

    public function setDefaultClassRoom(?ClassRooms $defaultClassRoom): static
    {
        $this->defaultClassRoom = $defaultClassRoom;

        return $this;
    }

    /**
     * @return Collection<int, TrainingFinancialItems>
     */
    public function getTrainingFinancialItems(): Collection
    {
        return $this->trainingFinancialItems;
    }

    public function addTrainingFinancialItem(TrainingFinancialItems $trainingFinancialItem): static
    {
        if (!$this->trainingFinancialItems->contains($trainingFinancialItem)) {

templates/trainings/parameters/dropdown_options.html.twig
<div class="dropdown-menu dropdown-menu-arrow">
    <a class="dropdown-item" href="{{path("training_parameters_timetable", {"training": training.id})}}">
        Toutes les options
    </a>
    {% if training.TrainingsOptions is not empty %}
        {% for option in training.TrainingsOptions %}
            {% set selected = '' %}
            {% if (options == option.shortName) %}
                {% set selected = ' active' %}
            {% endif %}
            <a class="dropdown-item {{selected}}" href="{{path("training_parameters_timetable_with_options", {"training": training.id, "options": option.shortName})}}">
                    {{option.shortName}}
            </a>
        {% endfor %}
    {% endif %}
</div>

templates/trainings/parameters/tab_financial.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="financial-items-params-table" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Type</th>
                <th>Source</th>
                <th>Quantité</th>
                <th>Valeur Unitaire</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for financialItem in training.trainingFinancialItems %}
                {% if financialItem.enumSourceObject is constant('App\\Config\\FinancialItemsSourceEnum::SourceLesson')%}
                    {#
                    {% set keyname = 'type_'~financialItem.lessonType.id %}
                    {% set volume = volumePerLessonType[keyname] | default(0) %}
                    #}
                    {% set volume = 'NB_H_COURS - '~financialItem.lessonType %}
                {% endif %}
                {% if financialItem.enumSourceObject is constant('App\\Config\\FinancialItemsSourceEnum::SourceStudent')%}
                    {% set volume = 'NB_Etudiant' %}
                {% endif %}
                {% if financialItem.enumSourceObject is constant('App\\Config\\FinancialItemsSourceEnum::SourceManual')%}
                    {% set volume = financialItem.quantity %}
                {% endif %}
                <tr>
                    <td>
                        {{financialItem.title}}
                    </td>
                    <td>
                        {{financialItem.enumTypeObject|trans() }}
                    </td>
                    <td>
                        {{financialItem.enumSourceObject|trans() }}
                    </td>
                    <td>
                        {{volume|default(0) }}
                    </td>
                    <td>
                         {{financialItem.value}}
                    </td>
                    <td class="text-end">
                        <div class="btn-list flex-nowrap justify-content-end">
                            {% if (is_granted('TRAINING_PARAMETERS_FINANCIAL|WRITE', training)) %}
                                <a href="{{path('training_edit_financial_item', {'training':training.id, 'tt':financialItem.id})}}" class="btn btn-ghost-warning">
                                    Modifier
                                </a>
                            {% endif %}
                            {% if (is_granted('TRAINING_PARAMETERS_FINANCIAL|DELETE', training)) %}
                                <a href="{{path('training_remove_financial_item', {'training':training.id, 'id':financialItem.id})}}" class="btn btn-ghost-danger">
                                    Supprimer
                                </a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
</div>

templates/trainings/parameters/tab_options.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="training-options-table" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Abbréviation</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for option in training.trainingsOptions %}
                <tr>
                    <td>
                        {{option.name}}
                    </td>
                    <td>
                        {{option.shortname}}
                    </td>
                    <td class="text-end">
                        <div class="btn-list flex-nowrap justify-content-end">
                            {% if (is_granted('TRAINING_PARAMETERS_OPTION|WRITE', training)) %}
                                <a href="{{path('training_add_option', {'training':training.id, 'tt':option.id})}}" class="btn btn-ghost-warning">
                                    Modifier
                                </a>
                            {% endif %}
                            {% if (is_granted('TRAINING_PARAMETERS_OPTION|DELETE', training)) %}
                                <a href="{{path('training_remove_option', {'training':training.id, 'id':option.id})}}" class="btn btn-ghost-danger">
                                    Supprimer
                                </a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
</div>

templates/trainings/parameters/tab_people.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="training-params-people--table" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Roles</th>
                <th>Statut</th>
                <th>Options</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for person in training.usersTrainings %}
                <tr>
                    <td>
                        {{person.user.displayName}}
                    </td>
                    <td>
                        {% set roles = [] %}
                        {% for role in person.rolesEnumForDisplay %}
                            {% set roles = roles | merge([role|trans()]) %}
                        {% endfor %}
                        {{roles|sort|join(', ')}}
                    </td>
                    <td>
                        {{ person.enumStatusObject|trans()}}
                    </td>
                    <td>
                        {{ person.trainingOptions.toArray|sort|join(', ')}}
                    </td>
                    <td class="text-end">
                        <div class="btn-list flex-nowrap justify-content-end">
                            {% if (is_granted('TRAINING_PARAMETERS_USER|WRITE', training)) %}
                                <a href="{{path('training_add_person', {'training':training.id, 'tt':person.id})}}" class="btn btn-ghost-warning">
                                    Modifier
                                </a>
                            {% endif %}
                            {% if(person.enumStatusObject.value == 'ACTIVE') %}
                                {% if (is_granted('TRAINING_PARAMETERS_USER|DELETE', training)) %}
                                    <a href="{{path('training_remove_person', {'training':training.id, 'id':person.id})}}" class="btn btn-ghost-danger">
                                        Désactiver
                                    </a>
                                {% endif %}
                            {% else %}
                                {% if (is_granted('TRAINING_PARAMETERS_USER|DELETE', training)) %}
                                    <a href="{{path('training_reactivate_person', {'training':training.id, 'id':person.id})}}" class="btn btn-ghost-danger">
                                        Réactiver
                                    </a>
                                {% endif %}
                            {% endif %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{path('training_delete_person', {'training':training.id, 'id':person.id})}}" class="btn btn-ghost-info">
                                    Supprimer
                                </a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
</div>

templates/trainings/parameters/tab_timeslots.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="timeslots-table" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>Type</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for timeslot in training.timeslots %}
                <tr>
                    <td>
                        {{timeslot.name}}
                    </td>
                    <td>
                        {{timeslot.startDate|format_datetime('short', 'short', locale='fr')}}
                    </td>
                    <td class="">
                        {{timeslot.endDate|format_datetime('short', 'short', locale='fr')}}
                    </td>
                    <td class="">
                        {{timeslot.timeSlotsTypes.name}}
                    </td>
                    <td class="text-end">
                        <div class="btn-list flex-nowrap justify-content-end">
                            {% if (is_granted('TRAINING_PARAMETERS_TIMESLOT|WRITE', training)) %}
                                <a href="{{path('training_add_timeslot', {'training':training.id, 'tt':timeslot.id})}}" class="btn btn-ghost-warning">
                                    Modifier
                                </a>
                            {% endif %}
                            {% if (is_granted('TRAINING_PARAMETERS_TIMESLOT|DELETE', training)) %}
                                <a href="{{path('training_remove_timeslot', {'training':training.id, 'id':timeslot.id})}}" class="btn btn-ghost-danger">
                                    Supprimer
                                </a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
</div>

templates/trainings/parameters/tab_timetable.html.twig
<div id='calendar-timetable-weekly-params' data-focus="{{focus}}" data-feed="{{ path('ajax_training_timetable_sessions_with_options', {'id': training.id, 'options':options} ) }}" data-new-event="{{ path('training_add_lessonsession', {'training': training.id, 'tt': 0} ) }}" class="w-100"></div>

templates/trainings/parameters/tab_topics.html.twig
{% set dataTableId = 'topics-table' %}
{% if (allowEditTopics) %}
    {% set dataTableId = 'topics-table-dashboard' %}
{% endif %}
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="{{dataTableId}}" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th>CM</th>
                <th>TD</th>
                <th>TP</th>
                <th>Vol. Total</th>
                {% if (allowEditTopics) %}
                    <th>Vol. Planifié</th>
                {% endif %}
                <th>U.E.</th>
                <th class="w-1"></th>
            </tr>
        </thead>
        <tbody>
            {% for topic in training.trainings %}
                <tr>
                    <td>
                        {{topic.topics.name}}
                    </td>
                    <td class="">
                        {{topic.cm}}
                    </td>
                    <td class="">
                        {{topic.td}}
                    </td>
                    <td class="">
                        {{topic.tp}}
                    </td>
                    <td class="">
                        {{topic.totalVolume}}
                    </td>
                    {% if (allowEditTopics) %}
                        <td 
                            class="
                                {% if(volumesByTopics[topic.id]|default(0) != topic.totalVolume) %}
                                    text-warning fw-bold
                                {% else %}
                                    text-success
                                {% endif %}
                            ">
                            
                            {{volumesByTopics[topic.id]|default(0)}} 
                        </td>
                    {% endif %}
                    <td>
                        {{topic.topicsGroups.name|default('NA')}}
                    </td>
                    <td class="text-end">
                        <div class="btn-list flex-nowrap justify-content-end">
                            {% if topic.description is not empty %}
                                <a class="btn btn-ghost-info" data-bs-toggle="offcanvas" href="#topic_desc_{{topic.id}}" role="button">
                                    Infos
                                </a>
                                <div class="offcanvas offcanvas-end" tabindex="-1" id="topic_desc_{{topic.id}}">
                                    <div class="offcanvas-header">
                                        <h2 class="offcanvas-title" id="offcanvasEndLabel">{{topic.topics.name}}</h2>
                                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                                    </div>
                                    <div class="offcanvas-body">
                                        <div class="text-left">
                                            {{topic.description | raw}}
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            {% if (allowEditTopics) %}
                                {% if (is_granted('TRAINING_PARAMETERS_TOPIC|WRITE', training)) %}
                                    <a href="{{path('training_add_topic', {'training':training.id, 'tt':topic.id})}}" class="btn btn-ghost-warning">
                                        Modifier
                                    </a>
                                {% endif %}
                                {% if (is_granted('TRAINING_PARAMETERS_TOPIC|DELETE', training)) %}
                                    <a href="{{path('training_remove_topic', {'training':training.id, 'id':topic.id})}}" class="btn btn-ghost-danger">
                                        Supprimer
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
</div>