src/Entity/Skills.php
<?php

namespace App\Entity;

use App\Repository\SkillsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SkillsRepository::class)]
class Skills
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $cursus_order = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $short_name = null;

    /**
     * @var Collection<int, LessonSessions>
     */
    #[ORM\ManyToMany(targetEntity: LessonSessions::class, inversedBy: 'skills')]
    private Collection $lesson_sessions;

    #[ORM\ManyToOne(inversedBy: 'skills')]
    #[ORM\JoinColumn(nullable: true)]
    private ?TopicsGroups $topics_group = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $inactive = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $professional = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $knowledge = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $performance = null;

    #[ORM\ManyToOne(inversedBy: 'skills')]
    private ?Users $teacher = null;

    #[ORM\Column(nullable: true)]
    private ?float $volume = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $period = null;

    public function __construct()
    {
        $this->lesson_sessions = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getShortName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCursusOrder(): ?int
    {
        return $this->cursus_order;
    }

    public function setCursusOrder(?int $cursus_order): static
    {
        $this->cursus_order = $cursus_order;

        return $this;
    }

    public function getShortName(): ?string
    {
        return $this->short_name;
    }

    public function setShortName(?string $short_name): static
    {
        $this->short_name = $short_name;

        return $this;
    }

    /**
     * @return Collection<int, LessonSessions>
     */
    public function getLessonSessions(): Collection
    {
        return $this->lesson_sessions;
    }

    public function addLessonSession(LessonSessions $lessonSession): static
    {
        if (!$this->lesson_sessions->contains($lessonSession)) {
            $this->lesson_sessions->add($lessonSession);
        }

        return $this;
    }

    public function removeLessonSession(LessonSessions $lessonSession): static
    {
        $this->lesson_sessions->removeElement($lessonSession);

        return $this;
    }

    public function getTopicsGroup(): ?TopicsGroups
    {
        return $this->topics_group;
    }

    public function setTopicsGroup(?TopicsGroups $topics_group): static
    {
        $this->topics_group = $topics_group;

        return $this;
    }

    public function getInactive(): ?\DateTimeInterface
    {
        return $this->inactive;
    }

    public function setInactive(?\DateTimeInterface $inactive): static
    {
        $this->inactive = $inactive;

        return $this;
    }

    public function getProfessional(): ?string
    {
        return $this->professional;
    }

    public function setProfessional(?string $professional): static
    {
        $this->professional = $professional;

        return $this;
    }

    public function getKnowledge(): ?string
    {
        return $this->knowledge;
    }

    public function setKnowledge(?string $knowledge): static
    {
        $this->knowledge = $knowledge;

        return $this;
    }

    public function getPerformance(): ?string
    {
        return $this->performance;
    }

    public function setPerformance(?string $performance): static
    {
        $this->performance = $performance;

        return $this;
    }

    public function getTeacher(): ?Users
    {
        return $this->teacher;
    }

    public function setTeacher(?Users $teacher): static
    {
        $this->teacher = $teacher;

        return $this;
    }

    public function getVolume(): ?float
    {
        return $this->volume;
    }

    public function setVolume(?float $volume): static
    {
        $this->volume = $volume;

        return $this;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(?string $period): static
    {
        $this->period = $period;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Ignore;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Désolé, cet email est refusé. Contactez nous !')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $deleted = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(nullable: true)]
    private ?string $avatarName = null;

    #[ORM\Column(nullable: true)]
    private ?int $avatarSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[Vich\UploadableField(mapping: 'avatars', fileNameProperty: 'avatarName', size: 'avatarSize')]
    #[Ignore]
    private ?File $avatarFile = null;

    #[ORM\OneToMany(mappedBy: 'teacher', targetEntity: TopicsTrainings::class)]
    private Collection $teachingTopics;

    #[ORM\OneToMany(mappedBy: 'teacher', targetEntity: LessonSessions::class)]
    private Collection $lessonSessions;

    #[ORM\OneToMany(targetEntity: Trainings::class, mappedBy: 'contentContact')]
    private Collection $trainingsContentContact;

    #[ORM\OneToMany(targetEntity: Trainings::class, mappedBy: 'scholarshipContact')]
    private Collection $trainingsScholarshipContact;

    #[ORM\OneToMany(targetEntity: Trainings::class, mappedBy: 'administrativeContact')]
    private Collection $trainingsAdministrativeContact;

    /**
     * @var Collection<int, AclPermissions>
     */
    #[ORM\OneToMany(targetEntity: AclPermissions::class, mappedBy: 'user')]
    private Collection $aclPermissions;

    /**
     * @var Collection<int, UsersPlaces>
     */
    #[ORM\OneToMany(targetEntity: UsersPlaces::class, mappedBy: 'user')]
    private Collection $usersPlaces;

    /**
     * @var Collection<int, UsersTrainings>
     */
    #[ORM\OneToMany(targetEntity: UsersTrainings::class, mappedBy: 'user')]
    private Collection $usersTrainings;

    /**
     * @var Collection<int, Skills>
     */
    #[ORM\OneToMany(targetEntity: Skills::class, mappedBy: 'teacher')]
    private Collection $skills;

    public function __construct()
    {
        //$this->ownedTrainings = new ArrayCollection();
        $this->teachingTopics = new ArrayCollection();
        $this->lessonSessions = new ArrayCollection();
        $this->trainingsContentContact = new ArrayCollection();
        $this->trainingsScholarshipContact = new ArrayCollection();
        $this->trainingsAdministrativeContact = new ArrayCollection();
        $this->aclPermissions = new ArrayCollection();
        $this->usersPlaces = new ArrayCollection();
        $this->usersTrainings = new ArrayCollection();
        $this->skills = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDeleted(): ?\DateTimeInterface
    {
        return $this->deleted;
    }

    public function setDeleted(?\DateTimeInterface $deleted): static
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getDisplayName() : ?string {
        return $this->getFirstname()." ".$this->getLastName();
    }

    public function __toString() : string {
        return $this->getDisplayName();
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function setAvatarFile(?File $imageFile = null): void
    {
        $this->avatarFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getAvatarFile(): ?File
    {
        return $this->avatarFile;
    }

    public function setAvatarName(?string $imageName): void
    {
        $this->avatarName = $imageName;
    }

    public function getAvatarName(): ?string
    {
        return $this->avatarName;
    }

    public function setAvatarSize(?int $imageSize): void
    {
        $this->avatarSize = $imageSize;
    }

    public function getAvatarSize(): ?int
    {
        return $this->avatarSize;
    }

    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
            'password' => $this->password,
        ];
    }

    /**
     * Restore security relevant data
     *
     * @param array $data
     */
    public function __unserialize(array $data): void
    {
        $this->id = $data['id'];
        $this->email = $data['email'];
        $this->password = $data['password'];
    }

    public function getAvatarUrl(): ?string {
        if(!empty($this->getAvatarName())) {
            $avatar = 'uploads/avatars/'.$this->getAvatarName();
        } else {
            $avatar = $this->getDefaultAvatar();
        }
        return $avatar;
    }
    
    public function getDefaultAvatar(): ?string {
        return 'static/avatars/default.png';
    }

    /**
     * @return Collection<int, TopicsTrainings>
     */
    public function getTeachingTopics(): Collection
    {
        return $this->teachingTopics;
    }

    public function addTeachingTopic(TopicsTrainings $teachingTopic): static
    {
        if (!$this->teachingTopics->contains($teachingTopic)) {
            $this->teachingTopics->add($teachingTopic);
            $teachingTopic->setTeacher($this);
        }

        return $this;
    }

    public function removeTeachingTopic(TopicsTrainings $teachingTopic): static
    {
        if ($this->teachingTopics->removeElement($teachingTopic)) {
            // set the owning side to null (unless already changed)
            if ($teachingTopic->getTeacher() === $this) {
                $teachingTopic->setTeacher(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LessonSessions>
     */
    public function getLessonSessions(): Collection
    {
        return $this->lessonSessions;
    }

    public function addLessonSession(LessonSessions $lessonSession): static
    {
        if (!$this->lessonSessions->contains($lessonSession)) {
            $this->lessonSessions->add($lessonSession);
            $lessonSession->setTeacher($this);
        }

        return $this;
    }

    public function removeLessonSession(LessonSessions $lessonSession): static
    {
        if ($this->lessonSessions->removeElement($lessonSession)) {
            // set the owning side to null (unless already changed)
            if ($lessonSession->getTeacher() === $this) {
                $lessonSession->setTeacher(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Trainings>
     */
    public function getTrainingsContentContact(): Collection
    {
        return $this->trainingsContentContact;
    }

    public function addTrainingsContentContact(Trainings $trainingsContentContact): static
    {

templates/trainings_exports/tabs/widgets/report_pdf.html.twig
    <div class="mt-4"></div>
    <style>
        table.export_report, table.export_report tbody tr, table.export_report tbody td {
            border: none !important;
            padding: 5px;
        } 
        table.export_report tbody tr.bordered, table.export_report tbody td.bordered {
            border: 1px solid black !important;
        }
    </style>
    <table align="center" width="100%" class="table export_report mb-3" style="page-break-after: always;" style="">
        <tr>
            <td rowspan="2" colspan="2" class="text-center align-middle" width="20%" height="10%">
                <img src="{{ asset('img/logo_beaup.png') }}" style="margin:auto; display:block" width="80%" height="80%">
            </td>
            <td colspan="8" class="text-center align-middle fs-5" style="">
                <b>Institution Beaupeyrat – Centre de formation</b><br/>
                <span class="fs-6"><br/>
                    9ter rue Pétiniaud Beaupeyrat - 87036 Limoges Cedex<br/>
                    Siret : 775 716 715 00013 – APE 8531 Z<br/>
                    Déclaration d’activité enregistrée sous le n° 748 700 407 87 auprès du Préfet de la région Nouvelle Aquitaine.<br/>
                    UFA du CFA ASPECT AQUITAINE - Campus François d'Assise - 2 Allée Marianne Loir - 33800 Bordeaux<br/>
                </span>
            </td>
        </tr>
        <tr>
            <td colspan="8" class="text-center align-middle fs-4">
                <b>{{training.shortTitle}} 
                    {% if training.trainingsOptions is not empty %}
                        - option {{reportData.trainingOptions | join(', ')}}
                    {% endif %}
                </b>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="text-center align-middle fs-2 pt-5">
                &nbsp;
            </td>
            <td colspan="8" class="text-center align-middle fs-2 pt-5 pb-5">
                <b>{{reportData.title}}</b>
            </td>
        </tr>
        <tr>
            <td colspan="10" class="text-left pl-2 align-middle fs-3 pt-4 pb-3">
                <div class=""><b>Liste d'émargement : </b></div>
            </td>
        </tr>
        {% if students is not empty%}
            <tr>
                <td class="text-center align-middle fs-5 bordered" colspan="2">Nom</td>
                <td class="text-center align-middle fs-5 bordered" colspan="2">Prenom</td>
                <td class="text-center align-middle fs-5 bordered" colspan="2">Qualité</td>
                <td class="text-center align-middle fs-5 bordered" colspan="4">Signature</td>
            </tr>
            {% for student in students %}
                <tr>
                    <td class="text-center align-middle fs-4 bordered p-3" colspan="2">{{student.user.lastname}}</td>
                    <td class="text-center align-middle fs-4 bordered p-3" colspan="2">{{student.user.firstname}}</td>
                    <td class="text-center align-middle fs-4 bordered p-3" colspan="2">
                        {% set roles = [] %}
                        {% for role in student.rolesEnumForDisplay %}
                            {% set roles = roles | merge([role|trans()]) %}
                        {% endfor %}
                        {{roles|sort|join(', ')}}
                    </td>
                    <td class="text-center align-middle fs-4 bordered p-3" colspan="4">&nbsp;</td>
                </tr>
            {% endfor %}
        {% endif %}
        <tr>
            <td colspan="10" class="text-left pl-2 align-middle fs-3 pt-4 pb-3">
                <div class=""><b>Contenu des discussions : </b></div>
            </td>
        </tr>
        <tr>
            <td colspan="10" class="text-left pl-2 align-middle fs-3 pt-4 pb-3">
                <div class="">{{reportData.description | raw}}</div>
            </td>
        </tr>
        <tr>
            <td colspan="10" class="text-end pt-5 align-middle fs-3 pb-3">
                <div class="">Fait à Limoges le {{reportData.day.format('d/m/Y') }} par {{reportData.referee.displayName}},</div>
            </td>
        </tr>

    </table>

templates/trainings_exports/tabs/widgets/signatures_tab.html.twig
    <div class="mt-4"></div>
    <style>
        table.signature tr, table.signature td {
            border-color: black;
            border: 1px solid black;
            padding: 5px;
        } 
    </style>
    <table align="center" width="100%" class="table table-bordered signature mb-3" style="page-break-after: always;" style="">
        <tr style="border-top:none !important; border-left:none; !important">
            <td rowspan="3" colspan="2" class="text-center align-middle" width="20%" height="10%" style="border-top:none !important; border-left:none; !important">
                <img src="{{ asset('img/logo_beaup.png') }}" style="margin:auto; display:block" width="80%" height="80%">
            </td>
            <td colspan="8" class="text-center align-middle fs-5" style="border-top: 1 px solib black;">
                <b>Institution Beaupeyrat – Centre de formation</b><br/>
                <span class="fs-6"><br/>
                    9ter rue Pétiniaud Beaupeyrat - 87036 Limoges Cedex<br/>
                    Siret : 775 716 715 00013 – APE 8531 Z<br/>
                    Déclaration d’activité enregistrée sous le n° 748 700 407 87 auprès du Préfet de la région Nouvelle Aquitaine.<br/>
                    UFA du CFA ASPECT AQUITAINE - Campus François d'Assise - 2 Allée Marianne Loir - 33800 Bordeaux<br/>
                </span>
            </td>
        </tr>
        <tr style="border-top:none !important; border-left:none; !important">
            <td colspan="8" class="text-center align-middle fs-5">
                <b>{{training.shortTitle}} - OPTION {{training_option}}</b>
            </td>
        </tr>
        <tr style="border-top:none !important; border-left:none; !important">
            <td colspan="8" class="text-center align-middle fs-5">
                <b>{{signatures_date}}</b>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="text-center align-middle fs-5">Horaire</td>
            {% for session in sessions %}
                <td class="text-center align-middle fs-5"><small>{{session.startHour}} - {{session.endHour}}</small></td>
            {% endfor %}
            {% if sessions|length < 8 %}
                {% set remainingCell = 8-sessions|length %}
                <td class="text-center align-middle fs-5" colspan="{{remainingCell}}"></td>
            {% endif %}
            {#
                {% for i in 1..(8-sessions|length) %}
                    <td class="text-center align-middle fs-5"><small>08h00-10h00</small></td>
                {% endfor %}
            #}
        </tr>
        <tr>
            <td colspan="2" class="text-center align-middle fs-5">Ressource</td>
            {% for session in sessions %}
                <td class="text-center align-middle fs-5" width="10%">{{session.resource}}</td>
            {% endfor %}
            {% if sessions|length < 8 %}
                {% set remainingCell = 8-sessions|length %}
                <td class="text-center align-middle fs-5" colspan="{{remainingCell}}" width="{{remainingCell*5}}%">&nbsp;</td>
            {% endif %}
        </tr>
        <tr>
            <td colspan="2" class="text-center align-middle fs-5">Cours</td>
            {% for session in sessions %}
                <td class="text-center align-middle fs-5" width="10%">{{session.topic}}</td>
            {% endfor %}
            {% if sessions|length < 8 %}
                {% set remainingCell = 8-sessions|length %}
                <td class="text-center align-middle fs-5" colspan="{{remainingCell}}" width="{{remainingCell*10}}%">&nbsp;</td>
            {% endif %}
        </tr>
        <tr>
            <td colspan="2" class="text-center align-middle fs-5">Intervenant</td>
            {% for session in sessions %}
                <td class="text-center align-middle fs-5">{{session.teacher}}</td>
            {% endfor %}
            {% if sessions|length < 8 %}
                {% set remainingCell = 8-sessions|length %}
                <td class="text-center align-middle fs-5" colspan="{{remainingCell}}"></td>
            {% endif %}
        </tr>
        {% if students is not empty%}
            {% for student_option, students_list in students %}
                {% if student_option == key_option %}
                    {% for student in students_list %}
                        <tr>
                            <td class="text-center align-middle fs-2" width="15%">{{student.user.lastname}}</td>
                            <td class="text-center align-middle fs-2" width="15%">{{student.user.firstname}}</td>
                            {% for session in sessions %}
                                <td></td>
                            {% endfor %}
                            {% if sessions|length < 8 %}
                                {% set remainingCell = 8-sessions|length %}
                                <td class="text-center align-middle fs-2" colspan="{{remainingCell}}"></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                {% endif %}

            {% endfor %}
        {% endif %}
        
        <tr>
            <td colspan="2" class="text-center">Signature Intervenant</td>
            {% for session in sessions %}
                <td class="text-center align-middle fs-2"></td>
            {% endfor %}
            {% if sessions|length < 8 %}
                {% set remainingCell = 8-sessions|length %}
                <td class="text-center align-middle fs-2" colspan="{{remainingCell}}">&nbsp;</td>
            {% endif %}
        </tr>
    </table>

templates/trainings_exports/tabs/widgets/tsf_pdf.html.twig
    <div class="mt-4"></div>
    <style>
        table.export_tsf, table.export_tsf tbody tr, table.export_tsf tbody td {
            border: none !important;
            padding: 5px;
        } 
        table.export_tsf, table.export_tsf tbody tr.bordered, table.export_tsf tbody tr td.bordered {
            border: 1px solid grey !important;
        }
    </style>
    <table align="center" width="100%" class="table export_tsf mb-3" style="page-break-after: always; border: none !important;" style="">
        <tbody>
            <tr class="b-none">
                <td rowspan="3" colspan="2" class="text-center align-middle" width="20%" height="10%">
                    <img src="{{ asset('img/logo_beaup.png') }}" style="margin:auto; display:block" width="80%" height="80%">
                </td>
                <td colspan="8" class="text-center align-middle fs-5" style="">
                    <b>Institution Beaupeyrat – Centre de formation</b><br/>
                    <span class="fs-6"><br/>
                        9ter rue Pétiniaud Beaupeyrat - 87036 Limoges Cedex<br/>
                        Siret : 775 716 715 00013 – APE 8531 Z<br/>
                        Déclaration d’activité enregistrée sous le n° 748 700 407 87 auprès du Préfet de la région Nouvelle Aquitaine.<br/>
                        UFA du CFA ASPECT AQUITAINE - Campus François d'Assise - 2 Allée Marianne Loir - 33800 Bordeaux<br/>
                    </span>
                </td>
            </tr>
            <tr>
                <td colspan="8" class="text-center align-middle fs-4">
                    <b>{{training.title}} 
                        {# if training.trainingsOptions is not empty %}
                            - option {{tsfData.trainingOptions | join(', ')}}
                        {% endif #}
                    </b>
                </td>
            </tr>
            <tr>
                <td colspan="8" class="text-center align-middle fs-4">
                    <b>TP - Administrateur d'Infrastructures Sécurisées{#{{training.cursus.name}}#}</b>
                </td>
            </tr>
            <tr>
                <td class="m-2">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="12" class="text-center align-middle">
                    <h2>C.{{skill.cursusOrder}} : {{skill.name}}</h2>
                </td>
            </tr>
            <tr class="table-active align-middle bordered border-light">
                <td colspan="12" class="text-center align-middle p-2">
                    Organisation pédagogique
                </td>
            </tr>
            <tr class="align-middle bordered">
                <td colspan="2" class="text-center align-middle p-1 text-muted bordered">
                    Unité d'enseignement
                </td>
                <td colspan="10" class="text-center align-middle p-1 pl-2 bordered">
                    {{skill.topicsGroup.name}}
                </td>
            </tr>
            <tr class="align-middle bordered">
                <td colspan="2" class="text-center align-middle p-1 text-muted bordered">
                    Volume
                </td>
                <td class="text-center align-middle p-1 pl-2 bordered">
                    {% if skill.volume is not empty %}
                        {{skill.volume}}H
                    {% else %}
                        &nbsp;
                    {% endif %}
                </td>
                <td colspan="2" class="text-center align-middle p-1 text-muted bordered">
                    Période
                </td>
                <td class="text-center align-middle p-1 pl-2 bordered">
                    {% if skill.period is not empty %}
                        {{skill.period}}
                    {% else %}
                        &nbsp;
                    {% endif %}
                </td>
                <td colspan="2" class="text-center align-middle p-1 text-muted bordered">
                    Intervenant
                </td>
                <td colspan="4" class="text-center align-middle p-1 pl-2 bordered">
                    {% if skill.teacher is not empty %}
                        {{skill.teacher.politeDisplayName}}
                    {% else %}
                        &nbsp;
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td class="m-2">&nbsp;</td>
            </tr>
            <tr class="table-active align-middle bordered border-light">
                <td colspan="12" class="text-center align-middle p-2">
                    Description métier
                </td>
            </tr>
            <tr class="align-middle bordered border-light">
                    <td colspan="12" class="text-center align-middle p-2">
                    {{skill.description|raw}}
                </td>
            </tr>
            <tr>
                <td class="m-2">&nbsp;</td>
            </tr>

            <tr class="table-active align-middle bordered border-light">
                <td colspan="6" class="text-center align-middle p-2 bordered">
                    Connaissances
                </td>
                <td colspan="6" class="text-center align-middle p-2 bordered">
                    Activités
                </td>
            </tr>
            <tr>
                <td colspan="6" class="text-left align-middle p-2 bordered">
                    {{skill.knowledge|raw}}
                </td>
                <td colspan="6" class="text-left align-middle p-2 bordered">
                    {{skill.professional|raw}}
                </td>
            </tr>
            <tr>
                <td class="m-2">&nbsp;</td>
            </tr>
            <tr class="table-active align-middle bordered border-light">
                <td colspan="6" class="text-center align-middle p-2">
                    Critères de performance
                </td>
                 <td colspan="6" class="text-center bordered align-middle p-2">
                    Modalités d'évaluation
                </td>
            </tr>
            <tr class="align-middle bordered border-light">
                <td colspan="6" class="text-left bordered align-middle p-2">
                    {{skill.performance|raw}}
                </td>
                <td colspan="6" class="text-left bordered align-middle p-2">
                    <ul>
                        <li><u>Pronostique</u> : par écrit dès la première semaine de formation</li>
                        <li><u>Sommative</u> : à la fin de chaque période via le suivi de projet</li>
                        <li><u>Certificative</u> : Soutenance orale au mois de juin</li>
                    <ul>
                </td>
            </tr>
        </tbody>
    </table>
        
    