src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Ignore;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Désolé, cet email est refusé. Contactez nous !')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $deleted = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(nullable: true)]
    private ?string $avatarName = null;

    #[ORM\Column(nullable: true)]
    private ?int $avatarSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[Vich\UploadableField(mapping: 'avatars', fileNameProperty: 'avatarName', size: 'avatarSize')]
    #[Ignore]
    private ?File $avatarFile = null;

    #[ORM\OneToMany(mappedBy: 'teacher', targetEntity: TopicsTrainings::class)]
    private Collection $teachingTopics;

    #[ORM\OneToMany(mappedBy: 'teacher', targetEntity: LessonSessions::class)]
    private Collection $lessonSessions;

    #[ORM\OneToMany(targetEntity: Trainings::class, mappedBy: 'contentContact')]
    private Collection $trainingsContentContact;

    #[ORM\OneToMany(targetEntity: Trainings::class, mappedBy: 'scholarshipContact')]
    private Collection $trainingsScholarshipContact;

    #[ORM\OneToMany(targetEntity: Trainings::class, mappedBy: 'administrativeContact')]
    private Collection $trainingsAdministrativeContact;

    /**
     * @var Collection<int, AclPermissions>
     */
    #[ORM\OneToMany(targetEntity: AclPermissions::class, mappedBy: 'user')]
    private Collection $aclPermissions;

    /**
     * @var Collection<int, UsersPlaces>
     */
    #[ORM\OneToMany(targetEntity: UsersPlaces::class, mappedBy: 'user')]
    private Collection $usersPlaces;

    /**
     * @var Collection<int, UsersTrainings>
     */
    #[ORM\OneToMany(targetEntity: UsersTrainings::class, mappedBy: 'user')]
    private Collection $usersTrainings;

    /**
     * @var Collection<int, Skills>
     */
    #[ORM\OneToMany(targetEntity: Skills::class, mappedBy: 'teacher')]
    private Collection $skills;

    public function __construct()
    {
        //$this->ownedTrainings = new ArrayCollection();
        $this->teachingTopics = new ArrayCollection();
        $this->lessonSessions = new ArrayCollection();
        $this->trainingsContentContact = new ArrayCollection();
        $this->trainingsScholarshipContact = new ArrayCollection();
        $this->trainingsAdministrativeContact = new ArrayCollection();
        $this->aclPermissions = new ArrayCollection();
        $this->usersPlaces = new ArrayCollection();
        $this->usersTrainings = new ArrayCollection();
        $this->skills = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDeleted(): ?\DateTimeInterface
    {
        return $this->deleted;
    }

    public function setDeleted(?\DateTimeInterface $deleted): static
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getDisplayName() : ?string {
        return $this->getFirstname()." ".$this->getLastName();
    }

    public function __toString() : string {
        return $this->getDisplayName();
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function setAvatarFile(?File $imageFile = null): void
    {
        $this->avatarFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getAvatarFile(): ?File
    {
        return $this->avatarFile;
    }

    public function setAvatarName(?string $imageName): void
    {
        $this->avatarName = $imageName;
    }

    public function getAvatarName(): ?string
    {
        return $this->avatarName;
    }

    public function setAvatarSize(?int $imageSize): void
    {
        $this->avatarSize = $imageSize;
    }

    public function getAvatarSize(): ?int
    {
        return $this->avatarSize;
    }

    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
            'password' => $this->password,
        ];
    }

    /**
     * Restore security relevant data
     *
     * @param array $data
     */
    public function __unserialize(array $data): void
    {
        $this->id = $data['id'];
        $this->email = $data['email'];
        $this->password = $data['password'];
    }

    public function getAvatarUrl(): ?string {
        if(!empty($this->getAvatarName())) {
            $avatar = 'uploads/avatars/'.$this->getAvatarName();
        } else {
            $avatar = $this->getDefaultAvatar();
        }
        return $avatar;
    }
    
    public function getDefaultAvatar(): ?string {
        return 'static/avatars/default.png';
    }

    /**
     * @return Collection<int, TopicsTrainings>
     */
    public function getTeachingTopics(): Collection
    {
        return $this->teachingTopics;
    }

    public function addTeachingTopic(TopicsTrainings $teachingTopic): static
    {
        if (!$this->teachingTopics->contains($teachingTopic)) {
            $this->teachingTopics->add($teachingTopic);
            $teachingTopic->setTeacher($this);
        }

        return $this;
    }

    public function removeTeachingTopic(TopicsTrainings $teachingTopic): static
    {
        if ($this->teachingTopics->removeElement($teachingTopic)) {
            // set the owning side to null (unless already changed)
            if ($teachingTopic->getTeacher() === $this) {
                $teachingTopic->setTeacher(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LessonSessions>
     */
    public function getLessonSessions(): Collection
    {
        return $this->lessonSessions;
    }

    public function addLessonSession(LessonSessions $lessonSession): static
    {
        if (!$this->lessonSessions->contains($lessonSession)) {
            $this->lessonSessions->add($lessonSession);
            $lessonSession->setTeacher($this);
        }

        return $this;
    }

    public function removeLessonSession(LessonSessions $lessonSession): static
    {
        if ($this->lessonSessions->removeElement($lessonSession)) {
            // set the owning side to null (unless already changed)
            if ($lessonSession->getTeacher() === $this) {
                $lessonSession->setTeacher(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Trainings>
     */
    public function getTrainingsContentContact(): Collection
    {
        return $this->trainingsContentContact;
    }

    public function addTrainingsContentContact(Trainings $trainingsContentContact): static
    {

src/Entity/UsersPlaces.php
<?php

namespace App\Entity;

use App\Config\UsersRolesPlacesEnum;
use App\Config\UsersStatusPlacesEnum;
use App\Repository\UsersPlacesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UsersPlacesRepository::class)]

class UsersPlaces
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'usersPlaces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $user = null;

    #[ORM\ManyToOne(inversedBy: 'usersPlaces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Places $place = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $permissions = null;

    #[ORM\UniqueConstraint(
        name: 'user_place_unique_idx',
        columns: ['user', 'place']
    )]

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPlace(): ?Places
    {
        return $this->place;
    }

    public function setPlace(?Places $place): static
    {
        $this->place = $place;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPermissions(): ?string
    {
        return $this->permissions;
    }

    public function setPermissions(?string $permissions): static
    {
        $this->permissions = $permissions;

        return $this;
    }

    public function getEnumStatusObject() {
        return UsersStatusPlacesEnum::tryFrom($this->getStatus());
    }

    public function getRolesEnumForDisplay() : array {
        $res = [];
        if(!empty($this->getRoles())) {
            foreach($this->getRoles() as $role) {
                $res[] = UsersRolesPlacesEnum::tryFrom($role);
            }
        }
        return $res;
    }

    public function generatePermsBasedOnRole(string $role):array {
        $res = [];
        switch($role) {
            case UsersRolesPlacesEnum::TEACHER->value:

            break;
            case UsersRolesPlacesEnum::STAFF->value:
                $res[] = 'PLACE_PARAMETERS|READ|'.$this->getPlace()->getId();
                $res[] = 'PLACE_PARAMETERS_CLASSROOM|READ|'.$this->getPlace()->getId();
            break;
            case UsersRolesPlacesEnum::MANAGEMENT->value:
                $res[] = 'PLACE_ALL|ALL|'.$this->getPlace()->getId();
            break;
            case UsersRolesPlacesEnum::ADMIN->value:
                $res[] = 'PLACE_ALL|ALL|'.$this->getPlace()->getId();
            break;
            default:
        }
        return $res;
    }
}

templates/places/parameters/tab_cursuses.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="place-cursuses-table" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Niveau</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for cursus in place.cursuses %}
                {% if cursus.inactive is null %}
                    <tr>
                        <td>
                            {{cursus.name}}
                        </td>
                        <td>
                            {{cursus.type.level}}
                        </td>
                        <td class="text-end">
                            <div class="btn-list flex-nowrap justify-content-end">
                                 {% if (is_granted('PLACE_PARAMETERS_CURSUS|WRITE', place)) %}
                                    <a href="{{path('place_add_cursus', {'place':place.id, 'tt':cursus.id})}}" class="btn btn-ghost-warning">
                                        Modifier
                                    </a>
                                {% endif %}
                                 {% if (is_granted('PLACE_PARAMETERS_CURSUS|DELETE', place)) %}
                                    <a href="{{path('place_remove_cursus', {'place':place.id,'id':cursus.id})}}" class="btn btn-ghost-danger">
                                        Désactiver
                                    </a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endif %}
            {%endfor%}
        </tbody>
    </table>
</div>

templates/places/parameters/tab_people.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="place-params-people--table" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Roles</th>
                <th>Statut</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for person in place.usersPlaces %}
                <tr>
                    <td>
                        {{person.user.displayName}}
                    </td>
                    <td>
                        {% set roles = [] %}
                        {% for role in person.rolesEnumForDisplay %}
                            {% set roles = roles | merge([role|trans()]) %}
                        {% endfor %}
                        {{roles|sort|join(', ')}}
                    </td>
                    <td>
                        {{ person.enumStatusObject|trans()}}
                    </td>
                    <td class="text-end">
                        <div class="btn-list flex-nowrap justify-content-end">
                            {% if (is_granted('PLACE_PARAMETERS_USER|WRITE', place)) %}
                                <a href="{{path('place_add_person', {'place':place.id, 'tt':person.id})}}" class="btn btn-ghost-warning">
                                    Modifier
                                </a>
                            {% endif %}
                            {% if(person.enumStatusObject.value == 'ACTIVE') %}
                                {% if (is_granted('PLACE_PARAMETERS_USER|DELETE', place)) %}
                                    <a href="{{path('place_remove_person', {'place':place.id, 'id':person.id})}}" class="btn btn-ghost-danger">
                                        Désactiver
                                    </a>
                                {% endif %}
                            {% else %}
                                {% if (is_granted('PLACE_PARAMETERS_USER|DELETE', place)) %}
                                    <a href="{{path('place_reactivate_person', {'place':place.id, 'id':person.id})}}" class="btn btn-ghost-danger">
                                        Réactiver
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {%endfor%}
        </tbody>
    </table>
</div>

templates/places/parameters/tab_rooms.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="place-classrooms-table" style="width:100%">
        <thead>
            <tr>
                <th>Nom</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for classRoom in place.classRooms %}
                {% if classRoom.inactive is null %}
                    <tr>
                        <td>
                            {{classRoom.name}}
                        </td>
                        
                        <td class="text-end">
                            <div class="btn-list flex-nowrap justify-content-end">
                                {% if (is_granted('PLACE_PARAMETERS_CLASSROOM|WRITE', place)) %}
                                    <a href="{{path('place_add_class_room', {'place':place.id, 'tt':classRoom.id})}}" class="btn btn-ghost-warning">
                                        Modifier
                                    </a>
                                {% endif %}
                                 {% if (is_granted('PLACE_PARAMETERS_CLASSROOM|DELETE', place)) %}
                                    <a href="{{path('place_remove_class_room', {'place':place.id, 'id':classRoom.id})}}" class="btn btn-ghost-danger">
                                        Désactiver
                                    </a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endif %}
            {%endfor%}
        </tbody>
    </table>
</div>

templates/places/parameters/tab_trainings.html.twig
<div class="table-responsive">
    <table class="table card-table table-vcenter text-nowrap datatable" id="place-trainings-table" style="width:100%">
        <thead>
            <tr>
                <th>Intitulé</th>
                <th>Niveau</th>
                <th class="w-1"></th>   
            </tr>
        </thead>
        <tbody>
            {% for training in place.trainings %}
                {% if training.inactive is null %}
                    <tr>
                        <td>
                            {{training.title}}
                        </td>
                        <td>
                           
                        </td>
                        <td class="text-end">
                            <div class="btn-list flex-nowrap justify-content-end">
                                 {% if (is_granted('PLACE_PARAMETERS_TRAINING|WRITE', place)) %}
                                    <a href="{{path('place_add_training', {'place':place.id, 'tt':training.id})}}" class="btn btn-ghost-warning">
                                        Modifier
                                    </a>
                                {% endif %}
                                 {% if (is_granted('PLACE_PARAMETERS_TRAINING|DELETE', place)) %}
                                    <a href="{{path('place_archive_training', {'place':place.id,'training':training.id})}}" class="btn btn-ghost-danger">
                                        Désactiver
                                    </a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endif %}
            {%endfor%}
        </tbody>
    </table>
</div>

templates/places/parameters/tabs_menu.html.twig
<ul class="nav nav-pills card-header-pills" data-bs-toggle="tabs" role="tablist">
    {% if (is_granted('PLACE_PARAMETERS_TRAINING|READ', place)) %}
        <li class="nav-item" role="presentation">
            <a href="{{path('places_parameters_trainings', {'place': place.id})}}" class="nav-link {{ (currentTab == 'trainings') ? 'active' : '' }}">
                Les formations
            </a>
        </li>
    {% endif %}
    {% if (is_granted('PLACE_PARAMETERS_CLASSROOM|READ', place)) %}
        <li class="nav-item" role="presentation">
            <a href="{{path('places_parameters_classrooms', {'place': place.id})}}" class="nav-link {{ (currentTab == 'rooms') ? 'active' : '' }}">
                Les salles
            </a>
        </li>
    {% endif %}
    {# Deactivated for now, needs to make deactivation per place and not global
        {% if (is_granted('PLACE_PARAMETERS_CURSUS|READ', place)) %}
            <li class="nav-item" role="presentation">
                <a href="{{path('places_parameters_cursuses', {'place': place.id})}}" class="nav-link {{ (currentTab == 'cursuses') ? 'active' : '' }}">
                    Les cursus
                </a>
            </li>
        {% endif %}
    #}
    {% if (is_granted('PLACE_PARAMETERS_USER|READ', place)) %}
        <li class="nav-item" role="presentation">
            <a href="{{path('places_parameters_people', {'place': place.id})}}" class="nav-link {{ (currentTab == 'people') ? 'active' : '' }}">
                Les utilisateurs
            </a>
        </li>
    {% endif %}
    {% if (addTxt is not empty) and (addLink is not empty) %}
        <li class="nav-item ms-auto" role="presentation">
            <a href="{{addLink}}" class="nav-link d-sm-inline-block text-primary">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                {{addTxt}}
            </a>
        </li>
    {% endif %}
</ul>